# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DQInteraction' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DQInteraction

  target 'DQInteractionTests' do
    inherit! :search_paths
pod 'Masonry'
    # Pods for testing
  end

  target 'DQInteractionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
